using JobSearchManagerBack.Entities;
using Microsoft.EntityFrameworkCore;

namespace JobSearchManagerBack.Data;

internal class SqlServerDbContext : DbContext
{
    public SqlServerDbContext(DbContextOptions<SqlServerDbContext> options)
        : base(options) { }

    // protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    // {
    //     // Log all requests into the console
    //     optionsBuilder.LogTo(Console.WriteLine);
    //     base.OnConfiguring(optionsBuilder);
    // }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<JobApplication>(entity =>
        {
            entity.HasKey(jobApp => new { jobApp.Id, jobApp.Guid });

            // Configure the Guid to be generated by the database
            // Explicitly tell EF not to include Guid in INSERT statements
            entity
                .Property(jobApp => jobApp.Guid)
                .HasDefaultValueSql("NEWID()")
                .ValueGeneratedOnAdd(); // Indique que la valeur est générée lors de l'ajout
        });

        base.OnModelCreating(modelBuilder);
    }

    public DbSet<JobApplication> JobApplications { get; set; }

    public DbSet<Status> Statuses { get; set; }
}
