using JobSearchManagerBack.Entities;
using Microsoft.EntityFrameworkCore;

namespace JobSearchManagerBack.Data;

/// <summary>
/// Describes the content of the SQL Server database and give access to it
/// </summary>
internal class SqlServerDbContext : DbContext
{
    public SqlServerDbContext(DbContextOptions<SqlServerDbContext> options)
        : base(options) { }

    // THESE LINES ARE FOR DEBUGGING PURPOSES ONLY
    // protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    // {
    //     // Log all requests into the console
    //     optionsBuilder.LogTo(Console.WriteLine);
    //     base.OnConfiguring(optionsBuilder);
    // }

    /// <summary>
    /// Defines the model of the database and its tables,
    /// enforces them if they were created before this call
    /// </summary>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<JobApplication>(entity =>
        {
            entity.HasKey(jobApp => new { jobApp.Id, jobApp.Guid });

            /* Configures the Guid to be generated by the database and
            ** explicitly tells EF not to include Guid in INSERT statements.
            ** ===> Avoids the error "Cannot insert explicit value for identity column
            in table 'JobApplications' when IDENTITY_INSERT is set to OFF" */
            entity
                .Property(jobApp => jobApp.Guid)
                .HasDefaultValueSql("NEWID()")
                .ValueGeneratedOnAdd(); // Indique que la valeur est générée lors de l'ajout
        });

        base.OnModelCreating(modelBuilder);
    }

    /// <summary>
    /// Job applications entities in the database
    /// </summary>
    public DbSet<JobApplication> JobApplications { get; set; }

    /// <summary>
    /// Statuses entities in the database
    /// </summary>
    public DbSet<Status> Statuses { get; set; }
}
